import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Built from the files in docs/, ordered by each file's `sidebar_position`.
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
